/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP FUNCTION IF EXISTS `HHMMToDecimal`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `HHMMToDecimal`(p_HHMM VARCHAR(10)) RETURNS decimal(4,2)
    DETERMINISTIC
BEGIN
    DECLARE v_hours INT DEFAULT 0;
    DECLARE v_minutes INT DEFAULT 0;
    DECLARE v_colon INT DEFAULT 0;
    DECLARE v_result DECIMAL(4,2) DEFAULT 0.00;

    
    IF p_HHMM IS NULL OR p_HHMM = '' THEN
        RETURN NULL;
    END IF;

    
    SET v_colon = INSTR(p_HHMM, ':');
    IF v_colon = 0 THEN
        RETURN NULL; 
    END IF;

    
    SET v_hours = CAST(SUBSTRING(p_HHMM, 1, v_colon - 1) AS UNSIGNED);
    SET v_minutes = CAST(SUBSTRING(p_HHMM, v_colon + 1) AS UNSIGNED);

    
    IF v_minutes < 0 OR v_minutes > 59 THEN
        RETURN NULL;
    END IF;

    
    SET v_result = v_hours + (v_minutes / 60);

    RETURN v_result;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
