/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP FUNCTION IF EXISTS `ComputeAddressHash`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `ComputeAddressHash`(p_Maildrop VARCHAR(50),
    p_Street   VARCHAR(50),
    p_Suite    VARCHAR(50),
    p_ZipCode  INT(5) UNSIGNED ZEROFILL
) RETURNS char(64) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    DECLARE v_input TEXT;

    SET v_input = CONCAT_WS('|',
        UPPER(TRIM(COALESCE(p_Maildrop, ''))),
        UPPER(TRIM(COALESCE(p_Street, ''))),
        UPPER(TRIM(COALESCE(p_Suite, ''))),
        LPAD(p_ZipCode, 5, '0')
    );

    RETURN SHA2(v_input, 256);
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
