/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `AllergiesDelete`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `AllergiesDelete`(
    IN p_Id BIGINT UNSIGNED
)
BEGIN
    DECLARE v_exists INT DEFAULT 0;
    DECLARE v_success TINYINT UNSIGNED DEFAULT 1;
    DECLARE v_message VARCHAR(255) DEFAULT '';

    
    SELECT COUNT(*) INTO v_exists
    FROM allergies
    WHERE Id = p_Id;

    IF v_exists = 0 THEN
        SET v_success = 0;
        SET v_message = 'Allergy not found';
    END IF;

    
    IF v_success = 1 THEN
        DELETE FROM allergies WHERE Id = p_Id;
        SET v_message = 'Allergy deleted';
    END IF;

    SELECT v_success AS Success,
           v_message AS Message;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
