/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `vitals_search`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `vitals_search`(
    IN p_StartDate DATETIME,
    IN p_EndDate DATETIME,
    IN p_MinSystolic INT UNSIGNED,
    IN p_MaxSystolic INT UNSIGNED,
    IN p_MinOxygen INT UNSIGNED,
    IN p_MaxOxygen INT UNSIGNED
)
BEGIN
    SELECT *
    FROM vitals
    WHERE (p_StartDate IS NULL OR RecordedAt >= p_StartDate)
      AND (p_EndDate IS NULL OR RecordedAt <= p_EndDate)
      AND (p_MinSystolic IS NULL OR Systolic >= p_MinSystolic)
      AND (p_MaxSystolic IS NULL OR Systolic <= p_MaxSystolic)
      AND (p_MinOxygen IS NULL OR Oxygen >= p_MinOxygen)
      AND (p_MaxOxygen IS NULL OR Oxygen <= p_MaxOxygen)
    ORDER BY RecordedAt DESC, Id DESC;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
