/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `flowsheet_values`;
CREATE TABLE IF NOT EXISTS `flowsheet_values` (
  `Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `EntryId` bigint(20) unsigned NOT NULL,
  `FieldId` bigint(20) unsigned NOT NULL,
  `NumericValue` decimal(10,2) DEFAULT NULL,
  `TextValue` text DEFAULT NULL,
  `EnumValue` varchar(255) DEFAULT NULL,
  `BooleanValue` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_FlowsheetValues_EntryId` (`EntryId`),
  KEY `IX_FlowsheetValues_FieldId` (`FieldId`),
  CONSTRAINT `FK_FlowsheetValues_Entries` FOREIGN KEY (`EntryId`) REFERENCES `flowsheet_entries` (`Id`),
  CONSTRAINT `FK_FlowsheetValues_Fields` FOREIGN KEY (`FieldId`) REFERENCES `flowsheet_fields` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
