<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseTools\Tools.csproj" />
    <ProjectReference Include="..\DbTools\DbTools.csproj" />
  </ItemGroup>

</Project>